version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_codetickets
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codetickets_db
    volumes:
      # Data
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - batch-network

networks:
  batch-network:
    driver: bridge

volumes:
  db-data: